### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by sffr-dev** [xxlifestyle/IC--Repair-Design-Project-#1]
1. Ссылку на телефон ставим через tel:
2. Все `svg` лучше вставлять через тег `img`, кружочки у слайдера сделайте средствами  CSS (`border-radius: 50%`), то же касается полосок возле иконок секций
3. Чекбокс не кастомизирован
4. Цвет текста в инпуте на черном фоне должен быть белым
5. Хотелось бы, чтоб стили кнопок переиспользовались
6. Нет мобильной версии

**Comment by dielit66** [comment]
правки внес

**Comment by sffr-dev** [comment]
1. В хедере убрать синее подчеркивание у ссылок
2. На мобильной версии на 375 - белая полоса справа. Это из-за того, что элементы не влезают в разрешение. Посмотрите на стили `page1-buttons` и еще по макету

**Comment by dielit66** [comment]
готово
