### ISSUE TITLE
Slider comments

### ISSUE THREAD

**Issue by sffr-dev** [xxlifestyle/IC--Repair-Design-Project-#2]
1. Слайдер должен быть цикличным
2. https://github.com/xxlifestyle/IC--Repair-Design-Project-/blob/31305e5fdfc4ed7bd6a5d75f09c51162f956f17d/script.js#L40-L42 https://github.com/xxlifestyle/IC--Repair-Design-Project-/blob/31305e5fdfc4ed7bd6a5d75f09c51162f956f17d/script.js#L44-L46 Вот эти элементы нужно выбирать через коллекцию `querySelectorAll` и обращаться через индекс. Т.е. не менять стили, а навешивать активный класс. Если у нас будет 6 слайдов - код сильно вырастет, особенно эти функции https://github.com/xxlifestyle/IC--Repair-Design-Project-/blob/31305e5fdfc4ed7bd6a5d75f09c51162f956f17d/script.js#L88 https://github.com/xxlifestyle/IC--Repair-Design-Project-/blob/31305e5fdfc4ed7bd6a5d75f09c51162f956f17d/script.js#L126

**Comment by dielit66** [comment]
правки внес
