### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by sffr-dev** [xxlifestyle/IC--Repair-Design-Project-#3]
Направление правильное, но
1. https://github.com/xxlifestyle/IC--Repair-Design-Project-/blob/36ebb9817bfc49d16d1f59f4599c9ed2b0c52f10/script.js#L49 Избегайте магических цифр. Лучше сравнивать с длиной массива `entities`
2. https://github.com/xxlifestyle/IC--Repair-Design-Project-/blob/36ebb9817bfc49d16d1f59f4599c9ed2b0c52f10/script.js#L70 https://github.com/xxlifestyle/IC--Repair-Design-Project-/blob/36ebb9817bfc49d16d1f59f4599c9ed2b0c52f10/script.js#L100 Обработчики событий тоже навешивать лучше через `forEach`

**Comment by dielit66** [comment]
closed
